// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smizbfjsujlnfpcwfaty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtaXpiZmpzdWpsbmZwY3dmYXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTkyNTksImV4cCI6MjA2MzE3NTI1OX0.RX4F0e-_4bAXN2sEdNVhd0ZUCVOt3BmsGYyHrkW6vZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);